import Head from 'next/head'
import Layout from 'components/Layout'
import styles from 'styles/Home.module.css'
import Hero from 'components/hero'
import Link from 'next/link'
import { getSortedPostsData } from 'lib/posts'
import Card from 'components/Card'

export async function getStaticProps () {
  const posts = getSortedPostsData()
  return posts
}

export default function Home ({ posts }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
      </Head>

      <Layout>
        <Hero />
        <div className='grid grid-cols-2 gap-x-6 gap-y-12'>
          {posts.map(({ id, title, body }) => (
            <div key={id}>
              <Link href={`/post/${id}`}>
                <a>
                  <Card
                    title={title}
                    body={body}
                  />
                </a>
              </Link>
            </div>
          ))}
        </div>
      </Layout>
    </div>
  )
}
