import Head from 'next/head'
import Layout from 'components/Layout'
import styles from 'styles/Home.module.css'
import Hero from 'components/hero'
import Section from 'components/section'
import { getSortedPostsData } from 'lib/posts'
export async function getStaticProps () {
  const posts = getSortedPostsData()
  return posts
}
export default function Home ({ posts }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
      </Head>

      <Layout>
        <Hero />
        <Section posts={posts} />
      </Layout>
    </div>
  )
}
